


services :
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5


  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 5s
      timeout: 10s
      retries: 5

  go-app:
    build:
      context:  ./services/registration-service/
      dockerfile: Dockerfile
    container_name: go-app
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=school
      - DB_HOST=postgres
      - DB_PORT=5432
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    command: ["./main"]

  spring-app:
    build:
      context: ./services/user-service/api/
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  fastapi:
    build:
      context: ./services/subject-service/  # Diretório onde está o Dockerfile e o código da aplicação FastAPI
    ports:
      - 8000:8000  # Mapeia a porta 8000 do contêiner para a porta 8000 do host
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/dbname  # URL do banco PostgreSQL


  angular-app:
    build:
      context: ./services/frontend/webapp/
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:4200"  # A porta que o Nginx usará para servir a aplicação
    depends_on:
      - go-app  # Caso o Angular precise interagir com o Go
      - spring-app  # Caso o Angular precise interagir com o Spring
    command: ["npm", "start"]  # Comando para rodar o servidor Angular
    
     