# FUNCIONA
# CRIA ALUNO
POST http://localhost:8081/users/create
Content-Type: application/json

{
  "name": "Pedro Certezas4",
  "rg": "000.000.000-01",
  "type": "Student",
  "address": {
    "street": "Dr Fernando Mendes Ribeiro",
	  "number": "000",
	  "zipcode": "92700-00"
  }
}

###
# FUNCIONA
# BUSCA ALUNO POR MATRICULA
GET http://localhost:8081/users/id/2

###
# FUNCIONA
# BUSCA ALUNO POR CORRESPONDENCIA DO NOME
GET http://localhost:8081/users/name/Pedro

###
#FUNCIONA
# BUSCA TODOS OS ALUNOS
GET http://localhost:8081/users